name: Testes Rails

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Configurar Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Instalar Dependências
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Configurar Banco de Dados
      run: |
        cp config/database.yml.ci config/database.yml
        bin/rails db:create db:schema:load

    - name: Rodar Testes
      run: |
        bin/rails test
